version: "3"
services:
  graphdb:
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    env_file:
      - ./graphData.env
    ports:
      - 7474:7474
      - 7687:7687
  api:
    restart: always
    container_name: api
    build: ./
    environment:
      - isProd=true
    volumes:
      - ./src:/app/travellerstopapi/src
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"
